default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-docstring-first
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
      - id: check-added-large-files
        stages: [pre-commit]
      - id: debug-statements
        stages: [pre-commit]
      - id: double-quote-string-fixer
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2
    hooks:
      - id: autopep8
        stages: [pre-commit]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        args: [--py37-plus, --add-import, "from __future__ import annotations"]
        stages: [pre-commit]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
        stages: [pre-commit]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        stages: [pre-commit]
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.0.2
    hooks:
      - id: pylint
        args: ["--rcfile=.pylintrc"]
        stages: [pre-commit]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.23.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
